RC.ns("RC.Lang.CloudFax");

RC.utils.Lang.extend(RC.Lang.CloudFax, {
    NO_FILES_ATTACHED : 'No files attached',
    ERROR_INVALID_SCHEDULE_DATE_FORMAT : 'Invalid schedule date format.',
    ERROR_SELECT_SCHEDULE_TIME : 'Please select schedule time.',
    ERROR_DATE_OLD : 'Date is older than current date',
    ERROR_ATTACH_AT_LEAST_ONE_DOCUMENT : 'You must attach at least one document or use a Cover Page in order to send a fax.',
    ERROR_INVALID_PHONE_NUMBER : 'Invalid phone number',
    ERROR_NO_RECIPIENTS : 'You have not added any recipients.',
    ERROR_COULD_NOT_SAVE : 'The information could not be saved. Please try again later.',
    ERR_MSG_FAX_PREMIUM_RATE_NUMBERS: 'Faxes to Premium rate numbers, beginning with 09, are not supported. Please enter a different number.',
    SCHEDULED_TO_SEND : 'Your fax has been scheduled to send',
    HAS_BEEN_PROCESSED : 'Your fax has been processed and will be sent in a moment',
    ERROR_CAN_NOT_BE_SENT : 'Fax message can not be sent',
    ERROR_FILE_NOT_BEEN_ATTACHED : 'The file you selected has not been attached. Please attach file before sending.',
    TYPE_FAX_NUMBER : 'Type Fax number',
    TO : 'To',
    CONTACTS : 'Contacts',
    USE_COVER_PAGE : 'Use Cover Page',
    COVER_PAGE : 'Cover Page',
    PREVIEW : 'Preview',
    COVER_PAGE_NOTE : 'Cover Page Note',
    DOCUMENT_TO_FAX : 'Documents To Fax',
    SUPPORTED_FORMATS : 'Supported formats',
    SEND_NOW : 'Send Now',
    SCHEDULE : 'Schedule',
    SEND_ON : 'Send on',
    SEND_A_FAX : 'Send a Fax',
    AT : 'at',
    AM:'AM',
    PM:'PM',

    ERROR_INVALID_NAME_OR_NUMBER : "Invalid name or number",
    UNNAMED_CONTACT : 'Unnamed contact',
    NO_CONTACTS_WIN_TITLE : 'No contacts',
    NO_CONTACTS_WIN_TEXT : 'Selected group does not contain any contact with fax number.',
    GROUP_MEMBERS_SKIP_PROMPT : 'The following members of the group were skipped since their contact records did not contain any fax numbers:',
    INTERNATIONAL_MEMBERS_SKIP_PROMPT : 'The following international numbers were skipped since international calling is currently disabled:',
    SKIPPED_MEMBERS_OF_GROUP : 'Skipped members of group',
    SELECT_CONTACT : 'Select contact',
    GROUP : "{0} (Group)",

    RECIPIENT_NUMBERS: 'Recipient\'s Fax Number(s)',
    WANT_COVER: 'I want a cover page',
    SELECT_A_COVER: 'Select a cover',
    COVER_NOTES: 'Cover Page Notes',
    ATTACH_FILES: 'Attach File(s)',
    AUTH_MESSAGE: 'Please authorize {0} CloudFax to access your {1} Documents.',
    AUTH_NOW: 'Authorize Now',
    UNLINK: 'Unlink {0} Account',
    ATTACH_SELECTED_FILES: 'Attach Selected File(s)',
    PLS_SELECT_ONE: 'Please select at least one file',
    UNLINK_CONFIRM: 'Unlinking your {0} account will remove any attachments you have added from that account. Do you still want to do this?',
    PARENT_FOLDER: 'Parent Folder',
    BOX: 'Box',
    DROPBOX: 'Dropbox',
    GOOGLE: 'Google',
    BOX_LINK: 'https://www.box.com',
    DROPBOX_LINK: 'https://www.dropbox.com',
    GOOGLE_LINK: 'https://drive.google.com',
    RETRY: 'Retry',
    RETRY_MESSAGE: 'Sorry, we didn\'t attach all your selected files successfully. The failed file(s):',
    RETRY_MESSAGE2: 'Do you want to retry? Click \'{0}\' to attach the failed file(s) again, \'{1}\' to back to the attached list.',
    EXCEED_TOTAL_MAX_SIZE: 'Attachments cannot exceed 20 MB.',
    EXCEED_SINGLE_MAX_SIZE: 'Individual attachment cannot exceed 5 MB.',
    CLOUDFAX_TEXT : 'I want to fax a document from my Box, Dropbox or Google Drive'
});
